language: csharp
solution: ./src/collectw.sln
install:
  - nuget restore ./src/collectw.sln
  - nuget install xunit.runners -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/collectw.sln
  - mono ./testrunner/xunit.runners.*/tools/xunit.console.exe ./src/CollectW.Tests/bin/Release/CollectW.Tests.dll