language: csharp
solution: ./src/collectw.sln
script:
  - xbuild /p:Configuration=Release src/collectw.sln
  - mono ./src/packages/xunit.runner.console.2.0.0/tools/xunit.console.exe ./src/CollectW.Tests/bin/Release/CollectW.Tests.dll